<?php include 'head.phtml'; ?>
					<!-- First Band (Image) -->
					<div class="row">
						<h1>Getting started</h1>
						<h2>Backend setup</h2>
						<p>
							Download our backend implementation, and upload it to your webserver.
						</p>
							<pre>git clone https://github.com/Castcloud/Castcloud.git</pre>
						<p>
							Go to example.com/management to run the install script. This will allso make 
							you your administrator credentials.
							You are now ready to go. 
						</p>
						<h2>Clients</h2>
						<h1 class="subheader"><small>The online podcast library.</small></h1>
						<a href="/clients" class="button">Get a Client</a>
						<a href="https://github.com/Castcloud/Castcloud/archive/master.zip" class="button">Download server</a>
					</div>
					<!-- Second Band (Image Left with Text) -->

					<div class="row">
						<div class="large-4 columns">
							<img src="http://placehold.it/400x300&text=[img]">
						</div>
						<div class="large-8 columns">
							<h4>This is a content section.</h4>
							<div class="row">
								<div class="large-6 columns">
									<p>
										Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.
									</p>
								</div>
								<div class="large-6 columns">
									<p>
										Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.
									</p>
								</div>
							</div>
						</div>
					</div>

					<!-- Third Band (Image Right with Text) -->

					<div class="row">
						<div class="large-8 columns">
							<h4>This is a content section.</h4>

							<p>
								Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.
							</p>

							<p>
								Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.
							</p>

						</div>
						<div class="large-4 columns">
							<img src="http://placehold.it/400x300&text=[img]">
						</div>
					</div>
<?php include 'foot.phtml'; ?>
