					<!-- Footer -->

					<footer class="row">
						<div class="large-12 columns">
							<hr />
							<div class="row">
								<div class="large-6 columns">
									<p>
										&copy; Copyright no one at all. Go to town.
									</p>
								</div>
								<div class="large-6 columns">
									<ul class="inline-list right">
										<li>
											<a href="#">Link 1</a>
										</li>
										<li>
											<a href="#">Link 2</a>
										</li>
										<li>
											<a href="#">Link 3</a>
										</li>
										<li>
											<a href="#">Link 4</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</footer>
				</section>
				<a class="exit-off-canvas"></a>
			</div>
		</div>

		<!-- Tail scripts -->
		<script src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.2.2/js/vendor/jquery.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.2.2/js/foundation.min.js"></script>
		<script>
$(document).foundation();
		</script>
	</body>
</html>