	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Foundation Template | Banded</title>
		
		<meta name="description" content="Documentation and reference library for ZURB Foundation. JavaScript, CSS, components, grid and more." />
		<meta name="author" content="ZURB, inc. ZURB network also includes zurb.com" />
		<meta name="copyright" content="ZURB, inc. Copyright (c) 2013" />
		
		<link rel="stylesheet" href="/foundation/css/normalize.css" />
		<link rel="stylesheet" href="/foundation/css/foundation.css" />
		
		<script src="/foundation/js/vendor/modernizr.js"></script>
	</head>
  