<!doctype html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en">
<?php include 'head.phtml'; ?>
	<body>
		<div class="off-canvas-wrap">
			<div class="inner-wrap">
<?php include 'nav.phtml'; ?>
<?php include 'offcanvas.phtml'; ?>
				<section class="main-section">
					<!-- First Band (Image) -->
					<div class="row">
						<div class="panel large-12 columns">
							<h1>Castcloud</h1>
							<h1 class="subheader"><small>The online podcast library.</small></h1>
							<a href="/clients" class="button">Get a Client</a>
							<a href="https://github.com/Castcloud/Castcloud/archive/master.zip" class="button">Download server</a>

						</div>
					</div>
					<!-- Second Band (Image Left with Text) -->

					<div class="row">
						<div class="large-4 columns">
							<img src="http://placehold.it/400x300&text=[img]">
						</div>
						<div class="large-8 columns">
							<h4>This is a content section.</h4>
							<div class="row">
								<div class="large-6 columns">
									<p>
										Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.
									</p>
								</div>
								<div class="large-6 columns">
									<p>
										Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.
									</p>
								</div>
							</div>
						</div>
					</div>

					<!-- Third Band (Image Right with Text) -->

					<div class="row">
						<div class="large-8 columns">
							<h4>This is a content section.</h4>

							<p>
								Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.
							</p>

							<p>
								Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.
							</p>

						</div>
						<div class="large-4 columns">
							<img src="http://placehold.it/400x300&text=[img]">
						</div>
					</div>

					<!-- Footer -->

					<footer class="row">
						<div class="large-12 columns">
							<hr />
							<div class="row">
								<div class="large-6 columns">
									<p>
										&copy; Copyright no one at all. Go to town.
									</p>
								</div>
								<div class="large-6 columns">
									<ul class="inline-list right">
										<li>
											<a href="#">Link 1</a>
										</li>
										<li>
											<a href="#">Link 2</a>
										</li>
										<li>
											<a href="#">Link 3</a>
										</li>
										<li>
											<a href="#">Link 4</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</footer>
				</section>

				<a class="exit-off-canvas"></a>
			</div>
		</div>

		<!-- Tail scripts -->
		<script src="/foundation/js/vendor/jquery.js"></script>
		<script src="/foundation/js/foundation.min.js"></script>
		<script>
$(document).foundation();
		</script>
	</body>
</html>
