				<nav class="top-bar hide-for-small" data-topbar>
					<ul class="title-area">
						<li class="name">
							<h1><a href="http://www.castcloud.org">Castcloud.org</a></h1>
						</li>
						<li class="toggle-topbar menu-icon">
							<a href="#">Menu</a>
						</li>
					</ul>
					
					<section class="top-bar-section">
						<!-- Right Nav Section -->
						<ul class="left">
							<li class="active">
								<a href="/doc">Documentation</a>
							</li>
							<li class="">
								<a href="/start">Getting Started</a>
							</li>
							<li class="">
								<a href="/clients">Clients</a>
							</li>
							<li class="">
								<a href="/providers">Providers</a>
							</li>
						</ul>
						
						<ul class="right">
							<li class="">
								<a href="https://github.com/Castcloud/Castcloud/archive/master.zip" target="_blank">Download</a>
							</li>
						</ul>
					</section>
				</nav>
				
				<nav class="tab-bar show-for-small" data-topbar>
					<section class="left-small">
						<a class="left-off-canvas-toggle menu-icon" ><span></span></a>
					</section>
					
					<section class="middle tab-bar-section">
						<h1 class="title">Castcloud.org</h1>
					</section>
				</nav>
				